### ISSUE TITLE
Unstable functions API DiscountApplicationStrategy message is wrong

### ISSUE THREAD

**Issue by AtulGargMT** [Shopify/shopify-function-javascript#9]
Hi,

Shopify has released an unstable version of DiscountApplicationStrategy which has additional value ALL (Apply all discounts with conditions that are satisfied.). This works fine except the discount messages, even though the messages are different for each discount but it shows the first one.

Below is my functions output
`{
  "discounts": [
    {
      "targets": [
        {
          "productVariant": {
            "id": "gid://shopify/ProductVariant/47076195238172"
          }
        }
      ],
      "value": {
        "percentage": {
          "value": "10"
        }
      },
      "message": "10% combo discount"
    },
    {
      "targets": [
        {
          "productVariant": {
            "id": "gid://shopify/ProductVariant/47076194222364"
          }
        }
      ],
      "value": {
        "percentage": {
          "value": "5"
        }
      },
      "message": "5% multiuser discount"
    }
  ],
  "discountApplicationStrategy": "ALL"
}`

but the message on both line items is same as 10% combo discount. Can this be fixed please?

**Comment by nickwesselman** [comment]
This API change is still `unstable` as there is work in progress. You can follow along here:

https://github.com/Shopify/function-examples/discussions/194
